export {default as LoginPage} from './Login/Login'
export {default as HomePage} from './HomePage/HomePage'
export {default as QRPage} from './QR/QR' 
export {default as ScanQRPage} from './ScanQR/ScanQR' 
export {default as RegisterAccountPage} from './RegisterAccount/RegisterAccount' 