
const SET_AUTH = 'SET_AUTH'
const SET_USER = 'SET_USER'
const RESET_AUTH = 'RESET_AUTH'
const SET_USERS = 'SET_USERS'
const SET_ROOMS = 'SET_ROOMS'
const ADD_SESSION = 'ADD_SESSION'
const SET_SESSIONS = 'SET_SESSIONS'
const ADD_ROOM = 'ADD_ROOM'
const DELETE_SESSION = 'DELETE_SESSION'
const SET_ROLES = 'SET_ROLES'
const EDIT_SESSION = 'EDIT_SESSION'
const DELETE_USER = 'DELETE_USER'
const DELETE_ROOM = 'DELETE_ROOM'
const EDIT_ROOM = 'EDIT_ROOM'

export default {
    SET_AUTH,
    SET_USER,
    RESET_AUTH,
    SET_USERS,
    SET_ROOMS,
    ADD_SESSION,
    SET_SESSIONS,
    ADD_ROOM,
    DELETE_SESSION,
    SET_ROLES,
    EDIT_SESSION,
    DELETE_USER,
    DELETE_ROOM,
    EDIT_ROOM
}